### ISSUE TITLE
Incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by sfmMilk** [terrarium-earth/Tempad#16]
![image](https://user-images.githubusercontent.com/103464532/167228291-f426c0ff-b092-4d7a-ab5f-6db07b3af611.png)

Not my image.

Anyways, the world disappears when the portal is lit, and the tempad portal is completely white with no shading while in use.

**Comment by qouteall** [comment]
https://github.com/qouteall/ImmersivePortalsMod/issues/1019

This is probably because Tempad use its own way of postprocessing https://github.com/Toadstool-Studios/Tempad/blob/1.18/Common/src/main/java/me/codexadrian/tempad/mixin/LevelRendererMixin.java#L20

It can disable the postprocessing when immptl is present `FabricLoader.INSTANCE.isModLoaded("imm_ptl_core")`

**Comment by CodexAdrian** [comment]
I guess as a fix I'll just use the old way of rendering when imm_ptl_core is present as it would be way too much work to rewrite how it works rn. But I dont really understand what that mod is doing to break this so badly...

**Comment by qouteall** [comment]
Someone reported that this issue still exists in MC 1.19.2 https://discord.com/channels/662271867431682058/671895714527182920/1065620640377352223
