### ISSUE TITLE
Bugs with iris/oculus in 1.19+

### ISSUE THREAD

**Issue by lajjjj** [terrarium-earth/Tempad#33]
Some bugs with iris or oculus installed on 1.19+:
- The portal's fancy option won't show, even though timedoorFancy is set to true in the config
- The portal scales weirdly depending on the FOV, but is normal if the FOV is 70
- In third person the portal becomes tiny, appearing in the bottom left side of the screen. It's same visual bug that happens when shaders are enabled in 1.19+

Pressing F1 renders the portal with the correct scale and placement, both in first and third person - although without the fancy render option still.

Video of the portal scaling depending on FOV + toggling F1: https://streamable.com/6ccfpe
Video of the third person bug + toggling F1: https://streamable.com/hunjk0

Everything worked fine when I tested it in 1.18.2, even with shaders enabled

**Comment by CodexAdrian** [comment]
timedoorFancy uses fancy rendering that is *very* finicky, so I find it extremely unlikely it will work with iris, and I do not plan on making them compatible. In fact, It probably won't work. the reason the option exists is to disable it when mods are incompatible with the rendering.

If something breaks with Iris or Oculus, then its on them, and I do not plan on fixing it, mods like that break so many things. It breaking between versions is especially weird because the rendering code is *exactly* the same between versions
