### ISSUE TITLE
[Forge] Duplicate portals after tp

### ISSUE THREAD

**Issue by JaisDK** [terrarium-earth/Tempad#4]
Version 1.1.0

![image](https://user-images.githubusercontent.com/15868585/158418896-d5c734d1-a5f1-4864-b2e0-3b8fdabbb78b.png)

A second unusable portal shows up at the target location after teleporting

**Comment by CodexAdrian** [comment]
This is intentional, is the portal not automatically closing at the target location? It’s just a visual effect since there’s a portal at the target location in the source material. The portal is made useless to prevent you from accidentally teleporting yourself back through it, but I could make it functional or configurable if that’s something people want

**Comment by JaisDK** [comment]
it only shows after teleporting, is this the intended behavior? a TVA portal can go both ways right, so it would probably be more accurate if you could go both ways. You can prevent the accidental teleport by having a teleport cooldown on the player (per portal)

**Comment by CodexAdrian** [comment]
I guess I could do that. This will be fun

**Comment by JaisDK** [comment]
It will also allow other players to tp to your location right?

**Comment by CodexAdrian** [comment]
Honestly don't have time to implement this rn
