### ISSUE TITLE
[Bug]: Scrolling with mouse wheel breaks list order

### ISSUE THREAD

**Issue by ghost** [terrarium-earth/Tempad#92]
### Bug Description

if you have 12 location saved in the tempad, when you save a new location then re-open the tempad, if you scroll with the mouse wheel to go lower, the list order breaks. it seens to have no type of order since they are no correlation with the locations.
![test1](https://github.com/terrarium-earth/Tempad/assets/157164153/c48aded2-4f77-4648-b9b5-ec6237300128)
![test1](https://github.com/terrarium-earth/Tempad/assets/157164153/5a4ee9e7-9474-4aaa-90f0-403f17fd715c)

### How to Reproduce?

1. get 12 location on tempad
2. add new location
3. re-open tempad tp menu 
4. scroll up or down with mouse wheel

### Expected Behavior

keep the order, not scramble completly

### Version

1.4.0

### Mod Loader Version

1.18.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
1.18 is no longer supported

**Comment by TheGMYeti** [comment]
Using the Tempad mod in the LPS SteamPunk mod pack (mc version 1.19.2, which you committed to 3 weeks ago) and I can confirm that the list still breaks when you scroll. I even know the reason, but I am not able to fix it right now.
`me.codexadrian.tempad.client.gui.RunProgramScreen::init()` & `me.codexadrian.tempad.client.gui.RunProgramScreen::tick()` use different code to fill the list. I can't tell if it is the only issue right now, but from what I can see the issue is cause by `init()` sorting the list while `tick()` doesn't. An issue I can see coming up is that it moves at most 12 items of `allLocations` to `shownLocationData` before sorting.
I might suggest either adding sorting before moving to `shownLocationData` for best experience, or removing the sort from `init` for a quick fix?
